E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Controllers/ShoppingController.cs
using System.Threading.Tasks;
using DNTBreadCrumb.Core;
using KEC.ECommerce.Data.UnitOfWork.Core;
using KEC.ECommerce.Web.UI.Helpers;
using KEC.ECommerce.Web.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;



namespace KEC.ECommerce.Web.UI.Controllers
{

    public class ShoppingController : Controller
    {
        private readonly IUnitOfWork _uow;

        public ShoppingController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            var cartActions = new ShoppingCartActions(_uow, HttpContext);
            var productQty = _uow.PublicationsRepository.Get(productId)?.Quantity;
            if (User.Identity.IsAuthenticated)
            {
                if (productQty >= quantity)
                {
                    await cartActions.AddItem(productId, quantity);
                }
                else
                {
                    ModelState.AddModelError("", $"only {productQty} piece(s) remaining");
                }
            }
            else
            {
                ModelState.AddModelError("", "Please login or sign up first");
            }
          
            return CreateView(cartActions, "_ShoppingCartPartial");
        }
        [Authorize]
        [BreadCrumb(Title = "Cart", Order = 1)]
        public IActionResult Cart()
        {
            var cartActions = new ShoppingCartActions(_uow, HttpContext);
            var model = new ShoppingCartViewModel(_uow, cartActions.ShoppingCart, true);
            return View(model);
        }
        private IActionResult CreateView(ShoppingCartActions cartActions, string view, bool includeItems = false,string errorMessage=null)
        {
            var model = new ShoppingCartViewModel(_uow, cartActions.ShoppingCart, includeItems);
            if (errorMessage != null)
            {
                ModelState.AddModelError("",errorMessage);
            }
            return PartialView(view, model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveFromCart(int productId)
        {
            var cartActions = new ShoppingCartActions(_uow, HttpContext);
            var cart = cartActions.ShoppingCart;
            cartActions.RemoveItem(productId);
            return CreateView(cartActions, "_ShoppingCartItemsPartial", true);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult DestroyCart()
        {
            var cartActions = new ShoppingCartActions(_uow, HttpContext);
            var cart = cartActions.ShoppingCart;
            cartActions.DestroyCart();
            return RedirectToAction("Dashboard", "Account");
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult CheckOut()
        {
            var cartActions = new ShoppingCartActions(_uow, HttpContext);
            var email = User.FindFirst("Email")?.Value;
            var orderId = cartActions.CreateOrder(email);
            return RedirectToAction("Payment", "Orders", new { orderId });
        }
    }
}

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>@ViewData["Title"] | KEC Store</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/owl/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="~/lib/owl/css/animate.css" />
        <link rel="stylesheet" href="~/lib/owl/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="~/css/fluid-typography.css" />
        <link rel="stylesheet" href="~/css/ribbon.css" />
        <link rel="stylesheet" href="~/css/spinner.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/divider.min.css" />
        <link rel="stylesheet" href="~/lib/metro/css/metro-all.min.css" />
        <link rel="stylesheet" href="~/lib/simple-pagination/css/simplePagination.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/form.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/segment.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/step.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/message.min.css" />
        <link rel="stylesheet" href="~/css/tables.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Production">

        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css"
              asp-fallback-href="~/lib/metro/css/metro-all.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/owl/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="~/lib/owl/css/animate.css" />
        <link rel="stylesheet" href="~/lib/owl/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/divider.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/form.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/segment.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/message.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui/components/step.min.css" />
        <link rel="stylesheet" href="~/css/fluid-typography.css" />
        <link rel="stylesheet" href="~/css/ribbon.css" />
        <link rel="stylesheet" href="~/css/spinner.css" />
        <link rel="stylesheet" href="~/css/tables.css" />
        <link rel="stylesheet" href="~/lib/simple-pagination/css/simplePagination.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    </environment>
    
</head>
<body>
    <header class="app-bar bg-red  fg-white app-bar-expand-md" data-role="appbar" id="main-appbar">
        <button type="button" class="hamburger menu-down hidden"><span class="line"></span><span class="line"></span><span class="line"></span></button>
        <a href="/" class="">
            <img src="~/images/white-logo.png" style="width:110px; height:60px!important;" />
        </a>
        <ul class="app-bar-menu">
            <li><a asp-action="Index" asp-controller="Home"><span class="mif-home icon"></span>Home</a></li>
            <li>@await Component.InvokeAsync("ProductsMenu")</li>
            <li><a href="#"><span class="mif-info icon"></span>About</a></li>
            <li id="shoppingcart">@await Component.InvokeAsync("ShoppingCart")</li>
        </ul>
        @if (User.Identity.IsAuthenticated)
        {
            <ul class="app-bar-menu ml-auto">
                <li><a asp-action="Dashboard" asp-active-route asp-hide-if-active="true" asp-controller="Account"><span class="mif-apps icon"></span>Dashboard</a></li>
                <li>
                    <a href="#" class="logout">
                        <form asp-action="Logout" id="logout-form" class="hidden" asp-controller="Account" method="POST"></form>
                        <span class="mif-user icon"></span>
                        @string.Concat("Logout", " ", User.FindFirst("DisplayName")?.Value)
                    </a>
                </li>

            </ul>
        }
        else
        {
            <ul class="app-bar-menu ml-auto">
                <li><a asp-action="Login" asp-controller="Account" asp-active-route asp-hide-if-active="true"><span class="mif-user icon"></span>Login</a></li>
                <li><a asp-controller="Account" asp-action="Register" asp-active-route asp-hide-if-active="true"><span class="mif-pencil icon"></span>Register</a></li>
            </ul>

        }
    </header>
    <div id="wrap" class="border bd-green">
        <div class="loading hidden" id="spinner">
            <div class="cssload-preloader">
                <div class="cssload-loader-inner">
                    <div class="cssload-cssload-loader-line-wrap-wrap">
                        <div class="cssload-loader-line-wrap"></div>
                    </div>
                    <div class="cssload-cssload-loader-line-wrap-wrap">
                        <div class="cssload-loader-line-wrap"></div>
                    </div>
                    <div class="cssload-cssload-loader-line-wrap-wrap">
                        <div class="cssload-loader-line-wrap"></div>
                    </div>
                    <div class="cssload-cssload-loader-line-wrap-wrap">
                        <div class="cssload-loader-line-wrap"></div>
                    </div>
                    <div class="cssload-cssload-loader-line-wrap-wrap">
                        <div class="cssload-loader-line-wrap"></div>
                    </div>
                </div>
            </div>
        </div>
        <div id="content" class="">
            <div class="grid">
                <div class="row">
                    <div class="cell-md-12 cell-sm-12">
                        <div class="p-1 m-1">
                            <div class="row">
                                <div class="cell-md-full">
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <breadcrumb asp-homepage-title="Account"
                                                    asp-homepage-url="@Url.Action("Dashboard", "Account", values: new { area = "" })"
                                                    asp-homepage-glyphicon="mif-user icon" style="background-color:#e8e8e8;"></breadcrumb>

                                    }
                                    else
                                    {
                                        <breadcrumb asp-homepage-title="Home"
                                                    asp-homepage-url="@Url.Action("Index", "Home", values: new { area = "" })"
                                                    asp-homepage-glyphicon="mif-home icon" style="background-color:#e8e8e8;"></breadcrumb>

                                    }
                                </div>
                            </div>
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="fg-white bg-red" id="footer">
            <footer class="footer-bg">
                
                    <div class="row" style="padding-top:20px;">
                        <div class="cell-md-3">
                            <img alt="Kenya Education Cloud" src="~/images/white-logo.png" style="width:110px; margin-left:90px; height:60px!important;" >
                            <p style="text-align:center;">
                                <b>Kenya Education Cloud</b><br>
                                2018 © Copyright
                            </p>
                        </div>
                        <div class="cell-md-3">
                            <h5>External Links</h5>

                            <ul style="font-size:12px;">
                                <li> <a target="_blank" style="color: inherit;" href="https://kicd.ac.ke/">Kenya Institute of Curriculum Development</a></li>

                                <li><a target="_blank" style="color: inherit;" href="http://www.education.go.ke/">Ministry of Education</a></li>
                                <li><a target="_blank" style="color: inherit;" href="http://icta.go.ke/">ICT Authority</a></li>
                                <li><a target="_blank" style="color: inherit;" href="http://icta.go.ke/digischool/">DigiSchool</a></li>
                                <li><a target="_blank" style="color: inherit;" href="http://www.tvetauthority.go.ke/">TVET Authority</a></li>
                                <li><a target="_blank" style="color: inherit;" href="http://elimika.ac.ke/">Elimika</a></li>
                                <li><a target="_blank" style="color: inherit;" href="http://kicdinteractivecontent.ac.ke/">Interactive Digital Content</a></li>
                                <li><a target="_blank" style="color: inherit;" href="https://www.knec.ac.ke/">Kenya National Examinations Council</a></li>
                            </ul>
                        </div>
                        <div class="cell-md-3">
                            <h5>Quick Links </h5>
                            <ul style="font-size:12px;">
                                <li><a style="color: inherit;" asp-controller="Home" asp-action="Index">Home</a></li>
                                @await Component.InvokeAsync("ProductsQuickLinks")
                                <li><a asp-action="Register" asp-controller="Account" style="color: inherit;">Register</a></li>

                            </ul>
                        </div>
                        <div class="cell-md-3">
                            <h5>Our Contacts</h5>

                            <p style="font-size:12px;">
                                <b>Kenya Education Cloud</b><br>
                                Desai Rd, Off Muranga Rd,<br>
                                Nairobi, Kenya.
                                <br>
                                <b>Phone Number</b><br>
                                +254 20 3749900 <br>
                                <b>Email</b> <br>
                                info@kicd.ac.ke
                            </p>
                        </div>
                    </div>
                    @*<div class="text-center mt-1 reduce-1">
                            <b>Kenya Education Cloud &copy; All Rights Reserved</b>
                        </div>*@
                
            </footer>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/jquery/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/lib/jquery/jquery.matchHeight-min.js"></script>
        <script src="~/lib/metro/js/metro.min.js"></script>
        <script src="~/lib/simple-pagination/js/jquery.simplePagination.js"></script>
        <script src="~/lib/owl//js/owl.carousel.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/jquery-3.3.1.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous">
        </script>
        <script src="~/lib/jquery/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/lib/jquery/jquery.matchHeight-min.js"></script>
        <script src="~/lib/simple-pagination/js/jquery.simplePagination.js"></script>
        <script src="https://cdn.metroui.org.ua/v4/js/metro.min.js" asp-fallback-src="~/lib/metro/js/metro.min.js"
                crossorigin="anonymous">
        </script>
        <script src="~/lib/owl/js/owl.carousel.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_LicenceListPartial.cshtml
@model LicencePageViewModel
<table class="table striped table-border cell-border">
    <thead>
        <tr>
            <th>Licence Code</th>
            <th>Publication</th>
            <th>Expiry Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var licence in Model.Licences)
        {
            <tr>
                <td class="licence">@licence.Code</td>
                <td class="licence">@licence.Publication</td>
                <td class="licence">@licence.ExpiryDate</td>
            </tr>
        }
    </tbody>
</table>

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_LineItemsPartial.cshtml
@using KEC.ECommerce.Web.UI.Models;
@model OrderViewModel
<table class="table striped table-border cell-border">
    <thead>
        <tr>
            <th>Product</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var lineItem in Model.Items)
        {
            <tr>
                <td class="orderitem">@lineItem.Description</td>
                <td class="orderitem">@lineItem.UnitPrice</td>
                <td class="orderitem">@lineItem.Quantity</td>
                <td class="orderitem">@lineItem.TotalCost</td>
            </tr>


        }
        <tr>
            <td class="orderitem"></td>
            <td class="orderitem"></td>
            <td class="orderitem" ><h5 style="color: #00b95f;" class="place-left-fs text-bold pr-2">Total Amount</h5></td>
            <td class="orderitem"><h5 style="color: #00b95f;" class="place-left text-bold pr-2">@Model.TotalCost</h5></td>
        </tr>

    </tbody>
</table>
@*<div class="row">
    <div class="cell-md-full clear">
        <h5 class="fg-blue place-right text-bold pr-2">@Model.TotalCost</h5>
    </div>
</div>*@

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_OrdersPartial.cshtml
@model IEnumerable<OrderViewModel>
<div class="row">
    <div class="cell-md-full">
        @{
            await Html.RenderPartialAsync("_ValidationErrorPartial");
        }
    </div>
</div>
<div class="row">
    <div class="cell-md-full">
        <table class="table striped table-border cell-border">
            <thead>
                <tr>
                    <th>Order Number</th>
                    <th>Date</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="orders">
                @foreach (var order in Model)
                {
                    <tr>
                        <td class="customer-order">@order.OrderNumber</td>
                        <td class="customer-order">@order.OrderDate</td>
                        <td class="customer-order">@order.ItemsCount</td>
                        <td class="customer-order">@order.TotalCost</td>
                        <td class="customer-order">
                            <form class="inline-form" asp-controller="Orders" asp-action="DeleteOrder" asp-route-orderId="@order.Id"
                                  data-ajax="true" data-ajax-update="#orders" data-ajax-method="DELETE" data-ajax-mode="replace"
                                  data-ajax-loading="#spinner" asp-antiforgery="true">
                                @Html.AntiForgeryToken()
                                <a role="button" asp-route-orderId="@order.Id" asp-controller="Orders" asp-action="Payment" class="button success outline rounded m-1 size-small"><span class="mif-money"></span>Pay</a>
                                <button type="submit" class="button alert outline rounded m-1 size-small"><span class="mif-bin"></span></button>
                            </form>
                        </td>
                    </tr>
                   
                }
            </tbody>
        </table>
    </div>
</div>

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_ProductDetailPartial.cshtml
@using KEC.ECommerce.Web.UI.Models;
@model ProductViewModel;
<link href="~/css/ImageCrop.css" rel="stylesheet" />
<div class="cell-md-2">
    <div class="card">
        <div class="card-header">
            <h6 class="text fg-green fg-red-hover">@Model.Subject</h6>
        </div>
        <div class="card-content p-2">
            <img src="@Url.Content(Model.ThumbnailUrl)" data-role="popover" data-popover-hide="5000" data-cls-popover="bg-blue fg-white drop-shadow"
                 data-popover-text="<div style='height:auto;width:250px; border-radius:5px; text-align:center; font-size:18px; background-color:#00B2EE;color:white'><b>Product Description</b><br>@Model.Description</div>" data-popover-position="right" class="img">
            @*class="img-thumbnail"*@
        </div>
        <div class="card-content">
            <div class="cell">
                <h5 class="text fg-green fg-red-hover">@Model.Author</h5>
            </div>
        </div>
        <div class="card-content">
            <div class="cell">
                <h5 class="text fg-green fg-red-hover">@Model.Title</h5>
            </div>
        </div>
        
        <div class="card-content">
            <div class="cell">
                <h5 class="text fg-green fg-red-hover">@Model.UnitPrice</h5>
            </div>
        </div>
        <div class="card-footer">
            @{
                await Html.RenderPartialAsync("_ShoppingForm", Model);
            }
        </div>
    </div>

</div>

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_PublicationListPartial.cshtml
@model ProductPageViewModel
@foreach (var product in Model.Products)
{
    await Html.RenderPartialAsync("_ProductDetailPartial", product);
}

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_PurchasesListPartial.cshtml
@model PurchasePageViewModel
<div class="row">
    <div class="cell-md-full">
        <table class="table striped table-border cell-border">
            <thead>
                <tr>
                    <th>Order Number</th>
                    <th>Date</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="orders">
                @foreach (var order in Model.Orders)
                {
                    <tr>
                        <td class="purchases">@order.OrderNumber</td>
                        <td class="purchases">@order.OrderDate</td>
                        <td class="purchases">@order.ItemsCount</td>
                        <td class="purchases">@order.TotalCost</td>
                        <td class="purchases">
                            <a role="button" asp-route-orderId="@order.Id" asp-controller="Account" asp-action="Purchase" 
                               class="button success outline rounded size-small"><span class="mif-eye"></span>View items</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_ShoppingCartItemsPartial.cshtml
@using KEC.ECommerce.Web.UI.Models;
@model ShoppingCartViewModel
<table class="table striped table-border cell-border">
    <thead>
        <tr>
            <th>Product</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cartItem in Model.Items)
        {
            <tr>
                <td class="cart">@cartItem.Description</td>
                <td class="cart">@cartItem.UnitPrice</td>
                <td class="cart">@cartItem.Quantity</td>
                <td class="cart">@cartItem.TotalCost</td>
                <td class="cart">
                    <form class="inline-form" asp-controller="Shopping" asp-action="RemoveFromCart" asp-route-productId="@cartItem.ProductId"
                          data-ajax="true" data-ajax-update="#mycart" data-ajax-method="DELETE" data-ajax-mode="replace"
                          data-ajax-loading="#spinner">
                        @Html.AntiForgeryToken()
                        <button class="button alert outline rounded m-1 size-small"><span class="mif-bin"></span></button>
                    </form>
                </td>
            </tr>
        }

        <tr>
            <td class="cart"></td>
            <td class="cart"></td>
            
            <td class="cart"> <h5 class="fg-blue place-left text-bold pr-2"></h5></td>
            <td class="cart">
                <h5 class="fg-blue place-left text-bold pr-2">@Model.TotalCost</h5>
            </td>
            <td></td>
        </tr>
    </tbody>
</table>

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_ShoppingCartPartial.cshtml
@using KEC.ECommerce.Web.UI.Models;
@model ShoppingCartViewModel;
@{
    await Html.RenderPartialAsync("_ValidationErrorPartial");
}
@if (Model != null && Model.ItemsCount > 0)
{
    <a asp-controller="Shopping" asp-active-route asp-hide-if-active="true" asp-action="Cart" id="cart"><span class="mif-cart icon"></span>My Cart<span class="badge badge-top m-1">@Model.ItemsCount</span></a>
}
else
{
    <span></span>

}

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_ShoppingForm.cshtml
@using KEC.ECommerce.Web.UI.Models;
@model ProductViewModel;

<form class="inline-form" asp-controller="Shopping" asp-action="AddToCart" asp-route-productId="@Model.Id"
      data-ajax="true" data-ajax-update="#shoppingcart" data-ajax-method="POST" data-ajax-mode="replace"
      data-ajax-loading="#spinner" data-ajax-success="notifySuccess" data-ajax-fail="notifyFail">
    @Html.AntiForgeryToken()
    <input type="number" class="w-50-md m-1" value="1" min="1"  name="quantity" />
    <button class="button success outline rounded m-1"><span class="mif-add-shopping-cart icon"></span>Add to cart</button>
</form>

E-Commerce/KEC.ECommerce/KEC.ECommerce.Web.UI/Views/Shared/_ValidationErrorPartial.cshtml
<div style="display:none">
    <div asp-validation-summary="All" class="fg-white p-2">
    </div>
</div>