Voucher/KEC.Voucher/KEC.Voucher.UI/KEC.Voucher.UI/Controllers/VoucherController.cs
using KEC.Voucher.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KEC.Voucher.UI.Controllers
{
   
    public class VoucherController : Controller
    {
       [CustomAuthorize(Roles = "Voucher Creator")]
        public ActionResult Index()
        {
            using (var context = new ApplicationDbContext())
            {
                var user = context.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
                var voucherUser = new VoucherUser
                {
                    Guid = user.Id,
                    FullName = user.FullName
                };
                return View(voucherUser);
            }
        }
      [CustomAuthorize(Roles = "Voucher Creator")]
        public ActionResult CreateVoucher()
        {
            using (var context = new ApplicationDbContext())
            {
                var user = context.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
                var voucherUser = new VoucherUser
                {
                    Guid = user.Id,
                    FullName = user.FullName
                };
                return View(voucherUser);
            }
        }
       [CustomAuthorize(Roles = "Voucher Approver")]
        public ActionResult ApproveVoucher()
        {
            using (var context = new ApplicationDbContext())
            {
                var user = context.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
                var voucherUser = new VoucherUser
                {
                    Guid = user.Id,
                    FullName = user.FullName
                };
                return View(voucherUser);
            }
        }
        [CustomAuthorize(Roles = "Voucher Approver ")]
        public ActionResult ManageVoucher()
        {
            using (var context = new ApplicationDbContext())
            {
                var user = context.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
                var voucherUser = new VoucherUser
                {
                    Guid = user.Id,
                    FullName = user.FullName
                };
                return View(voucherUser);
            }
        }
    }
}

Voucher/KEC.Voucher/KEC.Voucher.UI/KEC.Voucher.UI/Views/Voucher/CreateVoucher.cshtml
@{
    ViewBag.Title = "CreateVoucher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/plugins/footable/footable.all.min.js"></script>
<link href="~/Content/footable/footable.core.css" rel="stylesheet" />
<div id="wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    Kenya Education Cloud
                </h1>

            </div>
            <div class="alert alert-success hidden">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p id="alert" style=" text-align: center;"></p>
            </div>
            <div class="ibox float-e-margins">
                <div class="row">
                    <div class="ibox-title">
                        <div col-md-6>
                            <h5>Search For a  Batch / County To Create Vouchers</h5>
                        </div>
                        <div col-md-6>
                            <a href="@Url.Action("Index", "Voucher")" style="float:right; margin-right:20px;" class="btn btn-primary">
                                <span>BACK TO START</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    <input type="text" class="form-control input-sm m-b-xs" id="filter" placeholder="Search For Batch / County">

                    <table id="createdvouchers" class="footable table table-stripped" data-page-size="20" data-filter=#filter>
                        <thead>
                            <tr class="footable-sortable">
                                <th> BATCH NUMBER </th>
                                <th> COUNTY NAME </th>
                                <th> COUNTY CODE</th>
                                <th> SCHOOL TYPE</th>
                                <th> ACTIONS</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot>
                            <tr>
                                <td colspan="5">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>

        </div>
    </div>
    <div class="footer">

        <div>
            <strong>Copyright</strong> KICD &copy; 2018
        </div>
    </div>

</div>

<script type="text/JavaScript">
    function tableRows(data) {
        var tableRows = [];
        for (var i = 0; i < data.length; i++) {
            tableRows.push(drawRow(data[i]));
        }
        return tableRows;
    };
    //Start by getting voucher list based on batch Id

    reloadSchoolTypes();



    //This functionpopulates the tbody inner HTML with json data on call
    function drawRow(rowData) {

        var row = $("<tr />")
        row.append($('<td class="hidden"> + rowData.Id + </td>'));
        row.append($("<td>" + rowData.BatchNumber + "</td>"));
        row.append($("<td>" + rowData.CountyCode + "</td>"));
        row.append($("<td>" + rowData.CountyName + "</td>"));
        row.append($("<td>" + rowData.SchoolType + "</td>"));
        row.append($(`<td class="pull-right"> <button type="button" data-vid=${rowData.Id} class="btn btn-w-m btn-info btn-md NewBatch" role="button">CREATE VOUCHERS</button>`));
        return row[0];
    }
    function reloadSchoolTypes() {
        var d = new Date();
        var n = d.getFullYear();
        $.ajax({
            url: `https://voucherapi.kec.ac.ke/api/batches/${n}/withpendingvouchers`,
            type: "GET",
            dataType: "json",
            success: function (data, status, jqhxr) {
                console.log(data);

                //This code snipet prepares to append Json Data
                $('#createdvouchers>tbody').html(tableRows(data));
                hookCreateBatchButtons();
            },

        });
    }
    function hookCreateBatchButtons() {
        $('.NewBatch').click(function () {
            $(this).html('<i class="fa fa-refresh fa-spin"></i> Please wait');

            var bId = $(this).attr('data-vid');

            console.log($(this).attr('data-county'));
            $.ajax({
                headers :  {
                    'Accept' :  'application/json',
                    'Content-Type' :  'application/json'
                },
                beforeSend: function () {
                    if (!$('div.alert-success').attr('class').includes('hidden')) {
                        $('div.alert-success').toggleClass('hidden');
                    }
                },
                url: "https://voucherapi.kec.ac.ke/api/Vouchers",
                type: "POST",
                data: JSON.stringify({ BatchId: bId }),
                success: function (response, status, jxhr) {
                    console.log(response);
                    console.log(status);
                    $('#alert').html(`${response}`)
                    $('div.alert-success').toggleClass('hidden');
                    reloadSchoolTypes();

                }
            });
        });
    }
</script>

Voucher/KEC.Voucher/KEC.Voucher.UI/KEC.Voucher.UI/Views/Voucher/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/plugins/footable/footable.all.min.js"></script>
<link href="~/Content/footable/footable.core.css" rel="stylesheet" />
<div id="wrapper">
    <br>
    <div class="row">
        <div class="col-lg-4">
            <a href="#">
                <div class="widget style1 navy-bg">
                    <div class="row">

                        <div class="col-xs-12 text-right">
                            <span style="font-size:20px; color:black;"> Batches Available</span>
                            <h2 style="color:black;" id="batch">Loading...</h2>

                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4">
            <a href="#">
                <div class="widget style1 lazur-bg">
                    <div class="row">

                        <div class="col-xs-12 text-right">
                            <span style="font-size:20px; color:black;"> Vouchers Approved in KEC </span>
                            <h2 style="color:black;" id="voucher">Loading...</h2>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4">
            <a href="#">
                <div class="widget style1 yellow-bg">
                    <div class="row">

                        <div class="col-xs-12 text-right">
                            <span style="font-size:20px; color:black;"> Batches with Missing Vouchers </span>
                            <h2 id="vouchers">
                                <button class="btn btn-info" onclick="show()" style="font-size: 14px; color:black;">View List</button>
                            </h2>


                        </div>
                    </div>
                </div>
            </a>

        </div>
        <div class="col-lg-12" id="list">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row" class="form-group">
                        <div col-md-6>
                            <h5 style="margin-left:25px; margin-top:10px;color:black;">List Of Batches Available for Voucher Creation</h5>
                        </div>
                        <div col-md-6>
                            <a href="@Url.Action("CreateVoucher", "Voucher")" style="float:right; margin-right:20px;" class="btn btn-primary">
                                <span>CREATE THESE VOUCHERS</span>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>


                    </div>
                </div>
                <div class="ibox-content">
                    <div class="alert alert-success hidden">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <p id="message"></p>
                    </div>
                    <div class="alert alert-danger hidden">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <p id="error"></p>
                    </div>
                    <div class="table-responsive">
                        <table id="createdbatches" style="text-align:left;" class="footable table table-stripped toggle-arrow-tiny">
                            <tr>
                                <th class="hidden"> ID </th>
                                <th> BATCH NUMBER </th>
                                <th> COUNTY NAME </th>
                                <th> COUNTY CODE</th>

                            <tr>
                            <tfoot>
                                <tr></tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>

        </div>

        <div class="footer" style="">
            <strong>Copyright</strong> KEC  &copy; 2018
        </div>

    </div>
    <script type="text/JavaScript">
        function tableRows(data) {
            var tableRows = [];
            for (var i = 0; i < data.length; i++) {
                tableRows.push(drawRow(data[i]));
            }
            return tableRows;
        };
        //Start by getting voucher list based on batch Id
        var year = (new Date()).getFullYear();

        $.ajax({

            url: `https://voucherapi.kec.ac.ke/api/batches/${year}/withpendingvouchers`,
            type: "GET",
            dataType: "json",
            success: function (data, status, jqhxr) {
                console.log(data);

                //This code snipet prepares to append Json Data
                $('#createdbatches').append(tableRows(data));
                console.log(year);
            }
        });

        //This functionpopulates the tbody inner HTML with json data on call
        function drawRow(rowData) {
            var row = $("<tr />")
            row.append($(`<td id="bId" data-bachid=${rowData.Id} class="hidden">${rowData.Id}</td>`));
            row.append($("<td>" + rowData.BatchNumber + "</td>"));
            row.append($("<td>" + rowData.CountyName + "</td>"));
            row.append($("<td>" + rowData.CountyCode + "</td>"));
            row.append($(`<td id="sId" class="hidden"> + rowData.SchoolTypeId + </td>`));
            return row[0];
        }

        function CreateVouchers() {
            $('#newvoucher').html('<i class="fa fa-refresh fa-spin"></i> Please wait');
            var batchId = $('#bId').attr('data-bachid');


            console.log(`${batchId} `);
            $.ajax({
                headers : {
                    'Accept' : 'application/json',
                    'Content-Type' : 'application/json'
                },
                url: "https://voucherapi.kec.ac.ke/api/Vouchers",
                type: "POST",
                data: JSON.stringify({ BatchId: batchId }),
                success: function (response, status, jxhr) {
                    console.log(response);
                    console.log(status);

                    $('#message').html(` ${response}.`)
                    $('div.alert-success').toggleClass('hidden');
                    $('#newvoucher').html('CREATE VOUCHERS');

                },
                error: function (request, status, error) {
                    console.log(request);
                    console.log(status);

                    console.log(request.responseText);
                    $('#error').html(request.responseText)
                    $('div.alert-danger').toggleClass('hidden');
                    $('#newvoucher').html('CREATE VOUCHERS');
                }
            });
        }
    </script>

    <!--HAPPY CODDING TO YOU LAZZY TESTERS-->
    <script type="text/JavaScript">
        //getting voucheCounties and do a count
        $(document).ready(function () {
            var dd = new Date();
            var years = dd.getFullYear();
            var Count = $('#batch');
            $.ajax({
                url: `https://voucherapi.kec.ac.ke/api/batches/${years}/withpendingvouchers/count`,
                type: "GET",

                dataType: "json",
                success: function (data, status, jqhxr) {
                    console.log(data);
                    $('#batch').html(data)
                }
            });
        }) ;
    </script>
    <script type="text/JavaScript">
        //getting voucheCounties and do a count
        $(document).ready(function () {
            var d = new Date();
            var year = d.getFullYear();

            var Count = $('#voucher');
            $.ajax({
                url: ` https://voucherapi.kec.ac.ke/api/schools/approvedvouchers/${year}`,
                type: "GET",
                dataType: "json",
                success: function (data, status, jqhxr) {

                    console.log(year);
                    $('#voucher').html(data)
                }
            });
        }) ;
    </script>
    <script type="text/javascript">

        $("#list").hide();

        function show() {
            var x = document.getElementById("list");
            if (x.style.display === "block") {
                x.style.display = "none";
            } else {
                x.style.display = "block";
            }
        }
    </script>

Voucher/KEC.Voucher/KEC.Voucher.UI/KEC.Voucher.UI/Views/Voucher/ManageVoucher.cshtml
@{
    ViewBag.Title = "ManageVoucher";
}
@{
    var BatchNumber = Request.Params["batchNumber"];
    var SChoolType = Request.Params["schooltype"];
    var CountyName = Request.Params["county"];
    var BatchId = Request.Params["batchId"];
}
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/plugins/footable/footable.all.min.js"></script>
<link href="~/Content/footable/footable.core.css" rel="stylesheet" />

<div id="wrapper" class="gray-bg">
            <div class="form-group">
                <div class="panel panel-info text-justify">
                    <div class="panel-heading">BATCH INFORMATION</div>
                    <div class="panel-body">
                        <h4 id='batchId' data-batch=@BatchId><span><strong>Batch Number:</strong></span> @BatchNumber</h4>
                        <h4 id='schoolTypeId' data-schooltype=@SChoolType><span><strong>Shool Type:</strong></span>@SChoolType</h4>
                        <h4><span><strong>County Name:</strong></span> @CountyName</h4>
                   
                        <a href="@Url.Action("ApproveVoucher", "Voucher")" class="button btn btn-w-m btn-primary pull-right">
                            <span>BACK TO BATCH LIST</span>
                        </a>
                    </div>

                    <div class="panel-footer">


                    </div>
                </div>

                <div class="row">

                    <div class="col-sm-6">
                        <input type="checkbox" class="chk_approve" name="fancy-checkbox-default" id="fancy-checkbox-default" autocomplete="off" />
                        <label for="fancy-checkbox-default" class="[ btn btn-default active ]">SELECT ALL (APPROVAL) </label>
                    </div>
                    <div class="col-sm-6">
                        <div class="[ btn-group ] pull-right">
                            <button type="button" name="reject" id="reject" class="btn btn-w-m btn-danger btn-md">REJECT SELECTED</button>
                        </div>
                        <div class="[ btn-group ] pull-right">

                            <button type="button" name="approve" id="approve" class="btn btn-w-m btn-primary btn-md">APPROVE SELECTED</button>

                        </div>
                    </div>


                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h5>Serch For A School / Voucher</h5>


                            </div>
                            <div class="ibox-content">
                                <input type="text" class="form-control input-sm m-b-xs" id="filter"
                                       placeholder="Search For School / Voucher">

                                <table id="createdvouchers" class="footable table table-stripped" data-page-size="8" data-filter=#filter>

                                    <tr class="footable-sortable">


                                        <th style="display:none;"> ORDER </th>
                                        <th> SCHOOL NAME </th>
                                        <th> VOUCHER AMOUNT</th>
                                        <th> APPROVE</th>
                                        <th> REJECT</th>

                                    </tr>


                                    <tfoot>
                                        <tr>
                                            <td colspan="5">
                                                <ul class="pagination pull-right"></ul>
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
        <div class="footer">

            <div>
                <strong>Copyright</strong> KICD &copy; 2018
            </div>
        </div>

    <script>
        $(document).ready(function () {

            $('.footable').footable();
            $('.footable').footable();

        });

    </script>

    <script type="text/JavaScript">
        $(document).ready(function () {
            var batchId = $('#batchId').attr('data-batch');
            $.ajax({
                url: `https://voucherapi.kec.ac.ke/api/vouchers/created?batchId=${batchId}`,
                type: "GET",
                headers :  {
                    'Accept' :  'application/json',
                    'Content-Type' :  'application/json',
                    'Access-Control-Expose-Headers': '*'
                },
                dataType: "json",
                success: function (data, textStatus, jqXHR) {
                    console.log(jqXHR.getResponseHeader('page-Headers'));
                    //This code snipet prepares to append Json Data
                    $("#createdvouchers").append(tableRows(data));
                },
                complete: function (jqXHR, textStatus) {
                    console.log(jqXHR.getResponseHeader('page-Headers'));
                }
            });
        });
    </script>
    <!--  script to load counties stops here  -->
    <!--SCripts Start Here-->
    <script type="text/JavaScript">
        //Start by getting voucher list based on batch Id

        //This functionpopulates the tbody inner HTML with json data on call
        function tableRows(data) {
            var tableRows = [];
            for (var i = 0; i < data.length; i++) {
                tableRows.push(drawRow(data[i]));
            }
            return tableRows;
        }
        function drawRow(rowData) {
            var row = $("<tr />")
            row.append($("<td class='hidden'>" + rowData.Id + "</td>"));
            row.append($("<td>" + rowData.SchoolName + "</td>"));
            row.append($("<td>" + rowData.Amount + "</td>"));
            row.append($(`<td> <input type='checkbox' id=${rowData.Id} data-voucher=${rowData.Id} name=${rowData.Id} 'approve' class='approve'/> </td>`));
            row.append($(`<td> <input type='checkbox' id=${rowData.Id} data-voucher=${rowData.Id} name=${rowData.Id} 'reject' class='reject'/> </td>`));
            return row[0];
        }
        //This function Sends selected rows for rejection then replaces existeng rows with new rows
        function ajaxData() {
            var BatchId = $('#batchId').attr('data-batch');
            var voucherIdArray = []
            var checked = $('.reject:checked');
            $('.reject:checked').each((index, row) => {
                voucherIdArray.push(row['id'])
            });
            return JSON.stringify({ BatchId: BatchId, SelectedVouchers: voucherIdArray })
        };
        $('#reject').click(function (e) {
            e.preventDefault();
            console.log(ajaxData());
            $.ajax({
                headers :  {
                                    'Accept' :  'application/json',
                                    'Content-Type' :  'application/json',
                    'Access-Control-Allow-Origin': 'https://voucherapi.kec.ac.ke/api/'
                            },
                url: "https://voucherapi.kec.ac.ke/api/Vouchers/selected/reject",
                type: "PATCH",
                data: ajaxData(),
                success: function (data, status, jxhr) {
                    var remainingRows = tableRows(data);
                    var row = $("<tr/>");
                    row.append("<th> SCHOOL NAME </th>");
                    row.append("<th> VOUCHER AMOUNT</th>");
                    row.append("<th> APPROVE</th>");
                    row.append("<th> REJECT</th>");
                    remainingRows.unshift(row);
                    $('#createdvouchers>tbody').html(remainingRows);
                }
            });
        });
    </script>
    <!--This Script Checks the rejection checkbox-->
    <!--HAPPY CODDING TO YOU LAZZY TESTERS-->
    <!--SCripts Start Here-->
    <!--Start by getting voucher list based on batch Id-->
    <script type="text/JavaScript">
        function ajaxDatas() {
            var BatchId = $('#batchId').attr('data-batch');
            var voucherIdArray = []
            var checked = $('.approve:checked');
            $('.approve:checked').each((index, row) => {
                voucherIdArray.push(row['id'])
            });
            return JSON.stringify({ BatchId: BatchId, SelectedVouchers: voucherIdArray })
        };
        $('#approve').click(function (e) {
            e.preventDefault();
            console.log(ajaxDatas());
            $.ajax({
                headers :  {
                                    'Accept' :  'application/json',
                                    'Content-Type' :  'application/json',
                    'Access-Control-Allow-Origin': 'https://voucherapi.kec.ac.ke/api/'
                            },
                url: "https://voucherapi.kec.ac.ke/api/vouchers/selected/accept",
                type: "PATCH",
                data: ajaxDatas(),
                success: function (data, status, jxhr) {
                    var remainingRows = tableRows(data);
                    var row = $("<tr/>");
        
                    row.append("<th> SCHOOL NAME </th>");
                    row.append("<th> VOUCHER AMOUNT</th>");
                    row.append("<th> APPROVE</th>");
                    row.append("<th> REJECT</th>");
                    remainingRows.unshift(row);
                    $('#createdvouchers>tbody').html(remainingRows);
                }
            });
        });
    </script>
    <!--This Script Checks the Approve checkbox-->

    <script type="text/JavaScript">
        $(function () {
            $('.chk_approve').click(function () {
                $('.approve').prop('checked', this.checked);
            });
        });
    </script>
    <!--HAPPY CODDING TO YOU LAZZY TESTER-->